### ISSUE TITLE
License not shown if license_family is set

### ISSUE THREAD

**Issue by peterjc** [Anaconda-Platform/support#105]
Cross reference https://github.com/bioconda/bioconda-recipes/issues/4419

MIT example,
- https://bioconda.github.io/recipes/toolshed/README.html
  https://anaconda.org/bioconda/toolshed shows ``License: MIT License`` (worked!)
- https://bioconda.github.io/recipes/pyani/README.html
  https://anaconda.org/bioconda/pyani shows ``License: Unspecified`` (should be MIT)

BSD example:
- https://bioconda.github.io/recipes/wtforms-alchemy/README.html
  https://anaconda.org/bioconda/wtforms-alchemy shows  `` License: BSD License`` (worked!)
- https://bioconda.github.io/recipes/rdfextras/README.html
  https://anaconda.org/bioconda/rdfextras shows  ``License: Unspecified`` (should be BSD License)

Defined in their ``meta.yaml`` files as:

```
about:
  home: https://github.com/brentp/toolshed
  license: MIT License
  summary: 'flexible and easy file manipulation'
```

and:

```
about:
  home: http://widdowquinn.github.io/pyani/
  license: MIT License
  summary: 'pyani provides a package and script for calculation of genome-scale average nucleotide identity.'
  license_family: MIT
```

and:

```
about:
  home: https://github.com/kvesteri/wtforms-alchemy
  license: BSD License
  summary: 'Generates WTForms forms from SQLAlchemy models.'
```

and:

```
about:
  home: http://github.com/RDFLib/rdfextras
  license: BSD License
  summary: 'RDFExtras provide tools, extra stores and such for RDFLib.'
  license_family: BSD
```

It appears that including the supplementary information ``license_family:`` metadata breaks the license display on anaconda.org
