### ISSUE TITLE
Extraneous Output: when viewing notebooks

### ISSUE THREAD

**Issue by tonyfast** [Anaconda-Platform/support#37]
![image](https://cloud.githubusercontent.com/assets/4236275/15255849/6fec7fa8-190c-11e6-8b49-f8c08d24813b.png)

in `app.css` there is a weird statement in the output wrapper that add `Output:` to the notebook.

```css
#notebook .output_wrapper {
  margin: 2rem 0; }
  #notebook .output_wrapper:before {
    content: "Output:";
    float: left;
    width: 3.5rem;
    text-align: right;
    margin-right: 1.25rem; }
  #notebook .output_wrapper .output {
    margin-left: 4.5rem; }
  #notebook .output_wrapper .output_area {
    overflow-x: auto; }
```
